#![no_std] // don't link the Rust standard library
#![no_main] // disable all Rust-level entry points

#![feature(custom_test_frameworks)] // don't use the standard test framework. It depends on std
#![test_runner(crate::test_runner)] // the function that's going to be called by the main function generated by feature(custom_test_frameworks)
//#![test_runner(test_runner)] seems to work as well
#![reexport_test_harness_main = "test_main"] // rename the main function generated by feature(custom_test_frameworks) so we can call it manually from our entry point function

mod vga_buffer;

use core::panic::PanicInfo;


/// This function is called on panic.
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    println!("{}", info);
    loop {}
}

#[no_mangle] // don't mangle the name of this function
pub extern "C" fn _start() -> ! {
    println!("Hello World!\n\nTodays numbers are {} and {}.", 42, (2.0 / 3.0));

    #[cfg(test)]
    test_main();

    panic!("Some panic message (called from _start)");
}

#[cfg(test)]
fn test_runner(tests: &[&dyn Fn()]) {
    println!("Running {} tests", tests.len());
    for test in tests {
        test();
    }
}

#[test_case]
fn trivial_assertion() {
    print!("trivial assertion... ");
    assert_eq!(1, 1);
    println!("[ok]");
}
